export enum SettingKey {
  GOOGLE_TAG_MANAGER_KEY = 'GOOGLE_TAG_MANAGER_KEY',
  ADMIN_SMS_MOBILE_1 = 'ADMIN_SMS_MOBILE_1',
  PROPERTY_PROMOTE_DURATION = 'PROPERTY_PROMOTE_DURATION',
}

export enum SettingDataType {
  NUMBER = 'NUMBER',
  TEXT = 'TEXT',
  TEXT_AREA = 'TEXT_AREA',
}
