export enum SettingKey {
  GOOGLE_TAG_MANAGER_KEY = 'GOOGLE_TAG_MANAGER_KEY',
  PROPERTY_PROMOTE_DURATION = 'PROPERTY_PROMOTE_DURATION',
  CALL_CLICK_LIMIT = 'CALL_CLICK_LIMIT',
  CALL_CLICK_BAN_TTL = 'CALL_CLICK_BAN_TTL',
  CALL_CLICK_CHECKING_DURATION = 'CALL_CLICK_CHECKING_DURATION',
  JAYAB_MOBILE_NUMBER = 'JAYAB_MOBILE_NUMBER',
  JAYAB_MOBILE_FOR_ANNOUNCEMENTS = 'JAYAB_MOBILE_FOR_ANNOUNCEMENTS',
  JAYAB_MOBILE_FOR_TICKET_1 = 'JAYAB_MOBILE_FOR_TICKET_1',
  JAYAB_MOBILE_FOR_TICKET_2 = 'JAYAB_MOBILE_FOR_TICKET_2',
  PROPERTY_PHOTO_UPGRADE_PRICE = 'PROPERTY_PHOTO_UPGRADE_PRICE',
}

export enum SettingDataType {
  NUMBER = 'NUMBER',
  TEXT = 'TEXT',
  TEXT_AREA = 'TEXT_AREA',
}
