export const NOTIFICATION_ROUTE_GROUP = 'notifications';
export const ADMIN_NOTIFICATION_ROUTE_GROUP = `admin/${NOTIFICATION_ROUTE_GROUP}`;
export const USER_NOTIFICATION_ROUTE_GROUP = `user/${NOTIFICATION_ROUTE_GROUP}`;
