export enum AttachmentAdminFolder {
  BLOG = 'BLOG',
  BANNER = 'BANNER',
  CONTENT = 'CONTENT',
  PRODUCT = 'PRODUCT',
  CATEGORY = 'CATEGORY',
  BUSINESS = 'BUSINESS',
  BANNER_SM = 'BANNER_SM',
  BUSINESS_PRODUCT = 'BUSINESS_PRODUCT',
  OWNER_PROPERTY_IMAGE = 'OWNER_PROPERTY_IMAGE',
}

export enum AttachmentUserFolder {
  CHAT = 'CHAT',
  PROFILE = 'PROFILE',
  OWNER_SELFIE_IMAGE = 'OWNER_SELFIE_IMAGE',
  OWNER_PROPERTY_DOCS = 'OWNER_PROPERTY_DOCS',
  OWNER_PROPERTY_VIDEO = 'OWNER_PROPERTY_VIDEO',
  OWNER_PROPERTY_IMAGE = 'OWNER_PROPERTY_IMAGE',
  ADVISOR_DOCUMENT_IMAGE = 'ADVISOR_DOCUMENT_IMAGE',
  ADVISOR_NATIONAL_CARD_IMAGE = 'ADVISOR_NATIONAL_CARD_IMAGE',
}
