export enum AttachmentAdminFolder {
  BANNER = 'BANNER',
  BANNER_SM = 'BANNER_SM',
  CONTENT = 'CONTENT',
  CATEGORY = 'CATEGORY',
  PRODUCT = 'PRODUCT',
  BUSINESS = 'BUSINESS',
  BUSINESS_PRODUCT = 'BUSINESS_PRODUCT',
}

export enum AttachmentUserFolder {
  PROFILE = 'PROFILE',
  OWNER_SELFIE_IMAGE = 'OWNER_SELFIE_IMAGE',
  ADVISOR_NATIONAL_CARD_IMAGE = 'ADVISOR_NATIONAL_CARD_IMAGE',
  ADVISOR_DOCUMENT_IMAGE = 'ADVISOR_DOCUMENT_IMAGE',
  OWNER_PROPERTY_IMAGE = 'OWNER_PROPERTY_IMAGE',
  OWNER_PROPERTY_VIDEO = 'OWNER_PROPERTY_VIDEO',
  CHAT = 'CHAT',
  OWNER_PROPERTY_DOCS = 'OWNER_PROPERTY_DOCS',
}
