export enum AttachmentAdminFolder {
  BANNER = 'BANNER',
  BANNER_SM = 'BANNER_SM',
  CONTENT = 'CONTENT',
  CATEGORY = 'CATEGORY',
  PRODUCT = 'PRODUCT',
  BUSINESS = 'BUSINESS',
  BUSINESS_PRODUCT = 'BUSINESS_PRODUCT',
}

export enum AttachmentUserFolder {
  PROFILE = 'PROFILE',
  OWNER_SELFIE_IMAGE = 'OWNER_SELFIE_IMAGE',
}
